pipeline {
    agent any
    stages {
        stage('Test'){
            steps{
                sh 'echo hello'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                configFileProvider([configFile(fileId: 'situational_task2', variable: 'CONFIG_FILE')]){
                    sh "aws eks update-kubeconfig --region us-east-1 --name dev-eks"
                    sh "whoami"
                }
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'creds', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']])
                {
                    sh "kubectl apply -f k8s/"
                }
            }
        }
    }

    // post {
    //     success {
    //         echo 'Deployment successful'
    //     }
    //     failure {
    //         echo 'Deployment failed'
    //     }
    // }
}
